name: PEP8 Test
on: [push, pull_request]
jobs:
    test:
        name: PEP8 Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - run: pip install flake8
            - run: flake8 .

